### ISSUE TITLE
Zero responce from any buttons  from Linguistics menu

### ISSUE THREAD

**Issue by agricolamz** [silnrsi/libreoffice-linguistic-tools#16]
For some reason whatever I click from Linguistics menu (except `Help`) doesn't have any effects. Zero response. I mostly interested in `Data Conversion`. Should I try with the older versions of Linguistic Tools?

<details>

* Linux 5.3

* LibreOffice Version: 6.3.1.2

* Linguistics Tools 3.9.1

* SIL FLEx 8.3

* Python library lxml is installed

![image](https://user-images.githubusercontent.com/15956515/69013450-15456a00-0991-11ea-9931-a64ab9ae1db5.png)
</details>

**Comment by jkornelsen** [comment]
There is a problem with recent unreleased versions of LingTools. On Windows, often it requires two attempts in order for a menu option to work, and on some Linux systems, it has been reported to not work at all. This is likely caused by error handling or logging changes in the Python code, but I have not been able to track down the problem yet.

For now, if you encounter this problem, then use the final released version, which is LingTools 3.0. The new feature that builds a language-specific extension for spell checking, which uses lxml, is not available in version 3.0. Everything else should work, including core features such as importing interlinear texts and data conversion.

**Comment by agricolamz** [comment]
Dear @jkornelsen, thank you, version 3.0 works for me.

**Comment by jkornelsen** [comment]
Released version 3.9.2 with the problem fixed. Version 3.9.1 will not work on any variant of linux or mac. It turns out this is different from the two attempts problem, so I'll open a separate issue for that.
