### ISSUE TITLE
label contradiction

### ISSUE THREAD

**Issue by manebule** [silnrsi/libreoffice-linguistic-tools#21]
Thanks for the tool! I'm interested to see how it works. I'm just taking it for a spin, but have already found an issue: Linguistics > Get Interlinear Examples returns the error, "Please go to Grammar Settings and specify a file" if one has not done so yet. There is no "Grammar Settings" menu item, however, Linguistics > Interlinear Settings opens a window called "Grammar Settings". Suggest changing the error message and window title to "Interlinear Settings".

**Comment by jkornelsen** [comment]
Thanks for catching that. There are very many places where that phrase is used because it was a fundamental part of the initial design, but I've tried to update all of them for 4.0, so hopefully it will finally be fixed completely. I'm planning to release 4.0 in the next day or so, once the dictionary extension builder works with recent updates.

**Comment by manebule** [comment]
Great! Glad it helped,

Paul
________________________________
